dist: trusty
language: java
jdk: oraclejdk8
install: true
sudo: false # faster builds
cache:
  directories:
    - $HOME/.m2

before_install:
 - chmod +x gradlew

after_success:
  - bash <(curl -s https://codecov.io/bash) -v
